kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "ceph-rbd-provisioner.name" . }}
  labels:
{{ include "ceph-rbd-provisioner.labels" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ceph-rbd-provisioner.name" . }}-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "ceph-rbd-provisioner.name" . }}-clusterrole
  apiGroup: rbac.authorization.k8s.io
