apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ceph-rbd-provisioner.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "ceph-rbd-provisioner.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ceph-rbd-provisioner.name" . }}-role
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "ceph-rbd-provisioner.name" . }}-sa
  namespace: {{ .Release.Namespace }}
