apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ceph-rbd-provisioner.name" . }}-role
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "ceph-rbd-provisioner.labels" . | indent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
