apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ceph-rbd-provisioner.name" . }}-admin-secret
  labels:
{{ include "ceph-rbd-provisioner.labels" . | indent 4 }}
type: "kubernetes.io/rbd"
data:
  # ceph auth get-key client.admin | base64
  key: {{ required "adminKey is required filed" .Values.cephCluster.adminKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ceph-rbd-provisioner.name" . }}-secret
  labels:
{{ include "ceph-rbd-provisioner.labels" . | indent 4 }}
type: "kubernetes.io/rbd"
data:
  # ceph auth add client.kube mon 'allow r' osd 'allow rwx pool=kube'
  # ceph auth get-key client.kube | base64
  key: {{ required "userKey is required field" .Values.cephCluster.userKey }}
