kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.storageClass.name }}
  labels:
{{ include "ceph-rbd-provisioner.labels" . | indent 4 }}
provisioner: {{ .Values.provisioner.name }}
parameters:
  monitors: {{ required "Monitors field is required" .Values.cephCluster.monitors }}
  pool: {{ .Values.cephCluster.pool }}
  adminId: {{ .Values.cephCluster.adminId }}
  adminSecretNamespace: {{ .Release.Namespace }}
  adminSecretName: {{ include "ceph-rbd-provisioner.name" . }}-admin-secret
  userId: {{ .Values.cephCluster.userId }}
  userSecretNamespace: {{ .Release.Namespace }}
  userSecretName: {{ include "ceph-rbd-provisioner.name" . }}-secret
  imageFormat: {{ .Values.cephCluster.imageFormat | quote }}
  imageFeatures: {{ .Values.cephCluster.imageFeatures }}
